---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-apm-server
  labels:
    app: apmserver
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: apmserver
  template:
    metadata:
      labels:
        app: apmserver
    spec:
      volumes:
      - name: mt-apm-server-conf
        configMap:
          name: mt-apm-server
      containers:
      - name: apm-server
        image: mt-apm-server
        args:
        - -c
        - /etc/config/apm-server.yaml
        ports:
        - containerPort: 8200
        resources:
          limits:
            cpu: 1
            memory: "1Gi"
          requests:
            cpu: 1
            memory: "1Gi"
        volumeMounts:
        - name: mt-apm-server-conf
          mountPath: /etc/config
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mt-apm-server
data:
  apm-server.yaml: |
    apm-server:
      host: "0.0.0.0:8200"
      pprof:
        enabled: false
      expvar:
        enabled: false
      rum:
        enabled: true
        allow_origins: ['*']
        allow_headers: []
        source_mapping:
          enabled: true
          timeout: 5s
          cache.expiration: 5m
          index_pattern: "apm-*-sourcemap*"
          mtelasticsearch:
            tenant1:
              hosts: ["elasticsearch-es-http.tenant1.svc.cluster.local:9200"]
              #protocol: "https"
              username: "admin"
              password: "changeme"
            tenant2:
              hosts: ["elasticsearch-es-http.tenant2.svc.cluster.local:9200"]
              #protocol: "https"
              username: "admin"
              password: "changeme"
      kibana:
        enabled: false
    mtoutput:
      tenant1:
        elasticsearch:
          hosts: ["elasticsearch-es-http.tenant1.svc.cluster.local:9200"]
          enabled: true
          username: "admin"
          password: "changeme"
    mtoutput:
      tenant1:
        elasticsearch:
          hosts: ["elasticsearch-es-http.tenant1.svc.cluster.local:9200"]
          enabled: true
          username: "admin"
          password: "changeme"
      tenant2:
        elasticsearch:
          hosts: ["elasticsearch-es-http.tenant2.svc.cluster.local:9200"]
          enabled: true
          username: "admin"
          password: "changeme"
    # Temporary config to appease startup checks
    output.elasticsearch:
      hosts: ["elasticsearch-es-http.tenant1.svc.cluster.local:9200"]
      enabled: true
      username: "admin"
      password: "changeme"
    logging.level: warning
    http.enabled: false


